#!/bin/bash
#SlowDNS @PowerMX
# Definir variables para colores de texto
IP=$(curl -s -4 icanhazip.com)
HOST=`hostname`;
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variables para colores de fondo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetar cores
RESET='\033[0m'
slowdns () {
tput reset
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant SLOWDNS
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ────────── MENU SLOWDNS SSHPLUS ───────── ${YELLOW}"
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ──       Telegram: @TURBONET2023          ── ${YELLOW}"
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${RESET}"
echo -e "${YELLOW}SERVIDOR: ${WHITE}$IP\033[0m "
echo -e "${YELLOW}HOSTNAME: ${WHITE}$HOST\033[0m "
archivo="/etc/slowdns/infons"
if [ -e "$archivo" ]; then
    echo -ne "${YELLOW}SEU NS: ${WHITE} " && cat /etc/slowdns/infons
    echo -ne "${YELLOW}SUA CHAVE PÚBLICA: \033[0m " && cat /root/server.pub
else
    echo -e "${RED}SLOWDNS NÃO INSTALADO.\033[0m"
fi
    echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
    echo -e "${YELLOW}[${GREEN}01${YELLOW}]${WHITE} | INSTALAR SLOWDNS SSH"
    echo -e "${YELLOW}[${GREEN}02${YELLOW}]${WHITE} | INSTALAR SLOWDNS SSL"
    echo -e "${YELLOW}[${GREEN}03${YELLOW}]${WHITE} | INSTALAR SLOWDNS DROPBEAR"
    echo -e "${YELLOW}[${GREEN}04${YELLOW}]${WHITE} | INSTALAR SLOWDNS SOCKS"
    echo -e "${YELLOW}[${GREEN}05${YELLOW}]${WHITE} | VER INFORMAÇOES"
    echo -e "${YELLOW}[${GREEN}06${YELLOW}]${WHITE} | INICIAR SLOWDNS"
    echo -e "${YELLOW}[${GREEN}07${YELLOW}]${WHITE} | REINICIAR SLOWDNS"
    echo -e "${YELLOW}[${GREEN}08${YELLOW}]${WHITE} | PARAR SLOWDNS"
    echo -e "${YELLOW}[${GREEN}09${YELLOW}]${WHITE} | REMOVER SLOWDNS"
    echo -e "${YELLOW}[${GREEN}10${YELLOW}]${WHITE} | ATUALIZAR/REINSTALAR"
    echo -e "${YELLOW}[${GREEN}11${YELLOW}]${WHITE} | REMOVER SCRIPT"
    echo -e "${YELLOW}[${GREEN}00${YELLOW}]${WHITE} | SAIR"
    echo ""
    echo -ne "\033[0;36mO que deseja fazer?:\0033[m " && read opcao
    case $opcao in
    1) Opcao1 ;;
    2) Opcao2 ;;
    3) Opcao3 ;;
    4) Opcao4 ;;
    5) Opcao5 ;;
    6) Opcao6 ;;
    7) Opcao7 ;;
    8) Opcao8 ;;
    9) Opcao9 ;;
    10) Opcao10 ;;
    11) Opcao11 ;;
    0) Sair ;;
    *) "Calma Barboleta" ; echo ; slowdns ;;
    esac
    }

Opcao1 () {
    clear
    bash /etc/slowdns/slowdns-ssh
}

Opcao2 () {
    clear
    bash /etc/slowdns/slowdns-ssl
}

Opcao3 () {
    clear
    bash /etc/slowdns/slowdns-drop
}

Opcao4 () {
    clear
    bash /etc/slowdns/slowdns-socks
}


Opcao5 () {
    clear
    bash /etc/slowdns/slowdns-info
}

Opcao6 () {
    clear
    bash /etc/slowdns/startdns
}

Opcao7 () {
    clear
    bash /etc/slowdns/restartdns
}

Opcao8 () {
    clear
    bash /etc/slowdns/stopdns
}

Opcao9 () {
     clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
}

Opcao10 () {
    clear
    wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Slowdns/update
    chmod +x update
    bash update
}

Opcao11 () {
     clear
    bash /etc/slowdns/remove-slow
    echo -e "\033[0;31mSlowDNS Manager Desinstalado!\033[0m"
    sleep 2
    rm /bin/slowdns
}

Sair() {
    clear
    exit
}
clear
slowdns
